title: MoCapAct
description: A Multi-Task Dataset for Simulated Humanoid Control
authors: Nolan Wagener, Andrey Kolobov, Felipe Vieira Frujeri, Ricky Loynd, Ching-An Cheng, Matthew Hausknecht
buttons:
  Paper: 'https://arxiv.org/abs/2208.07363'
  Blog: 'https://www.microsoft.com/en-us/research/blog/mocapact-training-humanoid-robots-to-move-like-jagger/'
  Talk: 'https://www.youtube.com/watch?v=gzdz51zQV2s'
  Poster: 'https://www.dropbox.com/s/anjut7qu166qw9r/Poster.pptx?dl=0'
  Slides: 'https://www.dropbox.com/s/foo71jhd26ls8nb/Presentation%20%28Long%29.pptx?dl=0'
  Dataset: 'https://msropendata.com/datasets/201fda85-b888-40b6-9554-1832ef203c71'
  Code: 'https://github.com/microsoft/MoCapAct'
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
